name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy Production
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/deploy.yml
    with:
      env: prod
    secrets:
      firebase-token: ${{ secrets.FIREBASE_PROD_TOKEN }}
